---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: alerts
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: master
  url: https://github.com/cbx0n/homelab-iac
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alerts
  namespace: flux-system
spec:
  interval: 30s
  path: ./platform/alerts/discord/base
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: alerts
  targetNamespace: flux-system
  timeout: 3m0s
  wait: true
