---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  targetNamespace: longhorn-system
  install:
    createNamespace: True
  interval: 10m
  chart:
    spec:
      chart: longhorn
      version: '1.7.0'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 10m