---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/cbx0n/homelab-iac
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30s
  path: ./platform/metallb/base
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: metallb
  targetNamespace: metallb-system
  timeout: 3m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  dependsOn:
  - name: metallb
  interval: 30s
  path: ./platform/metallb/config
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: metallb
  targetNamespace: metallb-system
  timeout: 3m0s
  wait: true
