---
- name: Configure k3s agents
  hosts: k3s_agent
  become: true
  remote_user: ansible
  gather_facts: true
  roles:
    - configure-os
    - install-k3s

- name: Configure Cluster
  hosts: k3s
  become: true
  remote_user: ansible
  gather_facts: true
  roles:
    - configure-k3s-cluster