FROM --platform=amd64 alpine:3.20.1
ARG terraform_bin_file_url="https://releases.hashicorp.com/terraform/1.9.2/terraform_1.9.2_darwin_amd64.zip"
RUN ["wget ${terraform_bin_file_url}", "-O ~/terraform"]
ENTRYPOINT ["tail", "-f", "/dev/null"]