- name: Create Bind9 config files
  block:
  - name: Copy config files
    ansible.builtin.copy:
      dest: /usr/docker/bind9/
      src: ./files/

- name: Docker pull Bind9 Image
  community.docker.docker_image:
    name: ubuntu/bind9
    source: pull
    state: present
- community.docker.docker_container:
    name: bind9-container
    image: ubuntu/bind9
    state: started
    restart: true
    network_mode: host
    restart_policy: unless-stopped
    env:
      BIND9_USER: root
      TZ: "UTC"
    volumes:
      - /usr/docker/bind9/:/etc/bind/:rw