apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-unifi
spec:
  dnsNames:
  - unifi.cbxon.co.uk
  issuerRef:
    kind: ClusterIssuer
    name: cert-cluster-issuer
  secretName: unifi