apiVersion: v1
kind: Service
metadata:
  labels:
    app: unifi
  name: service-unifi
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: https
    name: https
  - port: 8080
    nodeport: 30100
    protocol: TCP
    targetPort: internal-comms
    name: internal-comms
  selector:
    app: unifi
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}