apiVersion: v1
kind: Service
metadata:
  labels:
    app: unifi
  name: service-unifi
spec:
  ports:
  - port: 8443
    protocol: TCP
    targetPort: webadmin
    name: webadmin
  - port: 8080
    protocol: TCP
    targetPort: device-comms
    name: device-comms
  - port: 1900
    protocol: UDP
    targetPort: cont-discovery
    name: cont-discovery
  - port: 10001
    protocol: UDP
    targetPort: ap-discovery
    name: ap-discovery
  - port: 3478
    protocol: UDP
    targetPort: unifi-stun
    name: unifi-stun
  selector:
    app: unifi
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}