apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-podinfo
  namespace: podinfo
  dnsNames:
  - podinfo.cbxon.co.uk
  issuerRef:
    kind: ClusterIssuer
    name: cert-cluster-issuer
  secretName: cert-podinfo