---
runner_arch: linux-x64
runner_version: 2.320.0
actions_join_token: ""
actions_repo_url: ""

apt_repositories:
  - name: hashicorp
    gpg_url: https://apt.releases.hashicorp.com/gpg
    gpg_store_location: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    repo: https://apt.releases.hashicorp.com
    distro: main
    stream: main

  - name: helm
    gpg_url: https://baltocdn.com/helm/signing.asc
    gpg_store_location: /usr/share/keyrings/helm.gpg
    repo: https://baltocdn.com/helm/stable/debian/
    distro: all
    stream: main

  - name: ansible
    gpg_url: https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=get&search=0x6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367
    gpg_store_location: /usr/share/keyrings/ansible-archive-keyring.gpg
    repo: http://ppa.launchpad.net/ansible/ansible/ubuntu
    distro: noble
    stream: main

additional_apt_packages:
  - terraform
  - packer
  - ansible
  - git
  - helm
