- name: Get K3s server token
  when: "'k3s_server' in group_names"
  block:
    - name: Create Auth K3s Token
      ansible.builtin.shell:
        cmd: k3s token create
      register: k3s_agent_join_token
      run_once: true

- set_fact: token={{ k3s_agent_join_token.stdout }}

- name: Join K3s agents to 
  when: "'k3s_agent' in group_names"
  block:
    - name: Copy K3s_Server service
      vars:
        - k3s_service_command: "k3s agent --server {{ k3s_master_url }} --token {{ token }}"
      ansible.builtin.template:
        dest: /etc/systemd/system/k3s.service
        src: ./files/k3s.service.j2
    - name: Enable & Start K3s Server service
      ansible.builtin.systemd_service:
        name: k3s
        enabled: true
    - name: Reboot K3s agents
      ansible.builtin.reboot:
        reboot_timeout: 30

- name: Install Longhorn on Cluster
  when: "'k3s_server' in group_names"
  block:
    - name: Kubectl apply Longhorn
      ansible.builtin.shell:
        cmd: k3s kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/{{ k3s_longhorn_version }}/deploy/longhorn.yaml