apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-mongodb
data:
  MONGODB_INITDB_ROOT_USERNAME: root
  MONGODB_INITDB_ROOT_PASSWORD: root
  MONGO_USER: unifi
  MONGO_PASS: unifi
  MONGO_DBNAME: unifi
  MONGO_AUTHSOURCE: admin
  init-mongodb: |
    #!/bin/bash

    if which mongosh > /dev/null 2>&1; then
      mongo_init_bin='mongosh'
    else
      mongo_init_bin='mongo'
    fi
    "${mongo_init_bin}" <<EOF
    use ${MONGO_AUTHSOURCE}
    db.auth("${MONGO_INITDB_ROOT_USERNAME}", "${MONGO_INITDB_ROOT_PASSWORD}")
    db.createUser({
      user: "${MONGO_USER}",
      pwd: "${MONGO_PASS}",
      roles: [
        { db: "${MONGO_DBNAME}", role: "dbOwner" },
        { db: "${MONGO_DBNAME}_stat", role: "dbOwner" }
      ]
    })
    EOF