apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unifi
  name: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi
  strategy: {}
  template:
    metadata:
      labels:
        app: unifi
    spec:
      containers:
      - image: mongo:4.4
        name: unifi-db
        env:
          - name: MONGODB_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: unifi-mongodb
                key: MONGODB_INITDB_ROOT_USERNAME
          - name: MONGODB_INITDB_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: unifi-mongodb
                key: MONGODB_INITDB_ROOT_PASSWORD
          - name: MONGO_USER
            valueFrom:
              configMapKeyRef:
                name: unifi-mongodb
                key: MONGO_USER
          - name: MONGO_PASS
            valueFrom:
              configMapKeyRef:
                name: unifi-mongodb
                key: MONGO_PASS
          - name: MONGO_DBNAME
            valueFrom:
              configMapKeyRef:
                name: unifi-mongodb
                key: MONGO_DBNAME
          - name: MONGO_AUTHSOURCE
            valueFrom:
              configMapKeyRef:
                name: unifi-mongodb
                key: MONGO_AUTHSOURCE
        volumeMounts:
        - name: init-mongodb
          mountPath: "/docker-entrypoint-initdb.d"
          readOnly: true
      volumes:
      - name: init-mongodb
        configMap:
          name: unifi-mongodb
          items:
          - key: "init-mongodb"
            path: "init-mongodb.sh"
status: {}