apiVersion: v1
kind: Service
metadata:
  labels:
    app: unifi
  name: unifi-db
  namespace: unifi
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: mongodb
  selector:
    app: unifi
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}