include "/etc/bind/named.conf.key";

controls {
    inet * port 953
    allow { 192.168.0.0/24; } keys { "tsig-key"; };
};

options {
    directory "/var/cache/bind";
	forwarders {
	  8.8.8.8;
	  8.8.4.4;
	};
    dnssec-validation auto;
    allow-query { any; };
};

zone "internal.cbxon.co.uk" IN {
    type master;
    file "/etc/bind/internal-cbxon-co-uk.zone";
    update-policy { grant tsig-key zonesub any; };
};