name: Cluster Deploy
on:
    push:
        branches: [master]
    workflow_dispatch: 

jobs:
    configure-runner:
        name: Configure Runner
        runs-on: self-hosted
        steps:
            - run: |
                echo "Host *" > ~/.ssh/config
                echo "  StrictHostKeyChecking no" >> ~/.ssh/config
                echo "Host github.com" >> ~/.ssh/config
                echo "  User git" >> ~/.ssh/config
                echo "[defaults]" > ~/.ansible.cfg
                echo "vault_id_match = true" >> ~/.ansible.cfg
                echo "vault_identity_list = cbxon@~/.ansible/cbxon-vault.pass" >> ~/.ansible.cfg
                git config --global user.email "runner@cbxon.co.uk"
                git config --global user.name "Actions Runner"
                echo "${{ secrets.ANSIBLE_VAULT }}" > ~/.ansible/cbxon-vault.pass

    terraform-plan-proxmox:
        name: Terraform Plan - Proxmox VM's
        runs-on: self-hosted
        needs: [ configure-runner ]
        defaults:
            run:
                working-directory: deploy-cluster
        outputs:
            tfplan: ${{ steps.tfplan.outputs.exitcode }}
        env:
            TF_TOKEN_app_terraform_io: ${{ secrets.HCP_TOKEN }}
        steps:
            - uses: actions/checkout@v4
            - run: ansible-vault decrypt secrets.terraform.auto.tfvars
            - run: terraform init
            - run: |
                set +e
                terraform plan -detailed-exitcode
                echo "exitcode=$?" >> "$GITHUB_OUTPUT"
              id: tfplan
              continue-on-error: true

    terraform-deploy-proxmox:
        name: Deploy Terraform - Proxmox VM's
        runs-on: self-hosted
        needs: [ terraform-plan-proxmox ]
        defaults:
            run:
                working-directory: deploy-cluster
        env:
            TF_TOKEN_app_terraform_io: ${{ secrets.HCP_TOKEN }}
            tfplan: ${{ needs.terraform-plan-proxmox.outputs.tfplan}}
        steps:
            - if: env.tfplan == 2
              run: |
                terraform apply --auto-approve

    # ansible-run:
    #     name: Ansible Run
    #     runs-on: self-hosted
    #     needs: [ terraform-deploy-proxmox ]
    #     steps:
    #         - run: ansible-playbook -i inventory/hosts playbook-k3s-cluster.yaml
    #           working-directory: ansible/plays
    #         - run: sed -i 's/127.0.0.1/192.168.0.211/' ~/.kube/config

    # terraform-plan-helm:
    #     name: Terraform Plan - Helm Charts
    #     runs-on: self-hosted
    #     needs: [ ansible-run ]
    #     defaults:
    #         run:
    #             working-directory: deploy-apps
    #     outputs:
    #         tfplan: ${{ steps.tfplan.outputs.exitcode }}
    #     steps:
    #         - uses: actions/checkout@v4
    #         - run: ansible-vault decrypt secrets.terraform.auto.tfvars
    #         - run: terraform init
    #         - run: |
    #             set +e
    #             terraform plan -detailed-exitcode
    #             echo "exitcode=$?" >> "$GITHUB_OUTPUT"
    #           id: tfplan
    #           continue-on-error: true

    # terraform-deploy-helm:
    #     name: Deploy Terraform - Helm Charts
    #     runs-on: self-hosted
    #     needs: [ terraform-plan-helm ]
    #     defaults:
    #         run:
    #             working-directory: deploy-apps
    #     env:
    #         tfplan: ${{ needs.terraform-plan-helm.outputs.tfplan}}
    #     steps:
    #         - if: env.tfplan == 2
    #           run: |
    #             terraform apply --auto-approve