name: Deploy Infrastructure
on:
    push:
        branches: [master]
    workflow_dispatch: 

jobs:
    configure-runner:
        name: Configure Runner
        runs-on: self-hosted
        steps:
            - run: |
                echo "Host *" > ~/.ssh/config
                echo "  StrictHostKeyChecking no" >> ~/.ssh/config
                echo "Host github.com" >> ~/.ssh/config
                echo "  User git" >> ~/.ssh/config
                echo "[defaults]" > ~/.ansible.cfg
                echo "vault_id_match = true" >> ~/.ansible.cfg
                echo "vault_identity_list = cbxon@~/.ansible/cbxon-vault.pass" >> ~/.ansible.cfg
                git config --global user.email "runner@cbxon.co.uk"
                git config --global user.name "Actions Runner"
                echo "${{ secrets.ANSIBLE_VAULT }}" > ~/.ansible/cbxon-vault.pass

    terraform-plan-proxmox:
        name: Terraform Plan - Proxmox VM's
        runs-on: self-hosted
        needs: [ configure-runner ]
        defaults:
            run:
                working-directory: deploy-cluster
        outputs:
            tfplan: ${{ steps.tfplan.outputs.exitcode }}
        env:
            TF_VAR_onepassword_service_account_token: ${{ secrets.ONEPASSWORD_TOKEN }}
            TF_TOKEN_app_terraform_io: ${{ secrets.HCP_TOKEN }}
            TF_WORKSPACE: "cluster_deploy_dev"
            TF_CLOUD_ORGANIZATION: "cbxon"
            TF_VAR_environment: dev
        steps:
            - uses: actions/checkout@v4
            - run: terraform init
            - run: |
                set +e
                terraform plan -var-file env/dev/terraform.tfvars -detailed-exitcode
                echo "exitcode=$?" >> "$GITHUB_OUTPUT"
              id: tfplan
              continue-on-error: true

    terraform-deploy-proxmox:
        name: Deploy Terraform - Proxmox VM's
        runs-on: self-hosted
        needs: [ terraform-plan-proxmox ]
        defaults:
            run:
                working-directory: deploy-cluster
        env:
            TF_VAR_onepassword_service_account_token: ${{ secrets.ONEPASSWORD_TOKEN }}
            TF_TOKEN_app_terraform_io: ${{ secrets.HCP_TOKEN }}
            TF_WORKSPACE: "cluster_deploy_dev"
            TF_CLOUD_ORGANIZATION: "cbxon"
            TF_VAR_environment: dev
            tfplan: ${{ needs.terraform-plan-proxmox.outputs.tfplan}}
        steps:
            - if: env.tfplan == 2
              run: |
                terraform init
                terraform apply -var-file env/dev/terraform.tfvars --auto-approve
